# Generated by Django 4.0.4 on 2022-07-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('food_category', models.CharField(max_length=100)),
                ('yelp_url', models.TextField(max_length=255)),
                ('personal_rating', models.IntegerField()),
            ],
        ),
    ]
