# Generated by Django 4.0.4 on 2022-07-12 19:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_restaurant_address_alter_restaurant_yelp_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='personal_rating',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
