# Generated by Django 4.0.4 on 2022-07-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_name_food_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-rating']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='certifications',
            field=models.ManyToManyField(to='main_app.certification'),
        ),
    ]
